server:
  port: 8080

spring:
  application:
    name: springboot-code-algorithm
  profiles:
    active: default
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration